### PR TITLE
Viewer update

### PR DESCRIPTION
**Pull request by tomkr**
Some smaller images for the licenses and a better way to generate the embed link.

### CODE REVIEW

**Comment by mzeinstra** [comment]
@o1da I apologise for the frequent pull request. This should be the last pull request for this week. I believe we have plenty of time before our presentation, so if you find time to merge this I would be very happy.

**Comment by o1da** [comment]
@mzeinstra it isn't problem :)
I'm waiting for @tomkr to response on #52 comment. But I can do it immediately.

**Comment by o1da** [comment]
Done, I really recommend to modify process of getting image size to avoid another query to IIIF server soon.

**Comment by tomkr** [comment]
@o1da Yeah, that's definitely the plan, but this was a quick fix for the presentation today. I'll add it as an issue on the embedr github.

**Pull request merged**
