### PR TITLE
Viewer updates

### PR DESCRIPTION
**Pull request by arjan**
commit cdf7d996cd983377a994aa244e6965f097f01122
Author: Arjan Scherpenisse arjan@scherpenisse.net
Date:   Wed Sep 23 15:23:02 2015 +0200

```
Lowercase the default metadata values

Fixes #68
```

commit 86ded22ac880258c2327c39b60ec52435ed82d63
Author: Maarten Zeinstra mzeinstra@MacBook-Air-Maarten.local
Date:   Wed Sep 23 15:24:03 2015 +0200

```
Changed width and height order in the region selection pop up

Solves #71
```

### CODE REVIEW

**Comment by mzeinstra** [comment]
This is a cosmetic change. If you have time to merge this pull request please do so during lunch or after CET working hours (either 12:00 - 13:00) or after 17:00 today or tomorrow. As we are doing a public demonstration of the product.

Please inform me when you intend to merge this.

**Comment by o1da** [comment]
I can do it now, but if it is OK I'm going to do it after 17:00 today.

**Comment by mzeinstra** [comment]
Now would be fine to! Thanks

**Comment by mzeinstra** [comment]
Or after 17:00 either way, I need to be aware so that we don't present at the same time. (presentation time is somewhere during the day)

**Comment by o1da** [comment]
It is online

**Comment by mzeinstra** [comment]
Thanks Oldrich!

**Pull request merged**
