### PR TITLE
Add React viewer.

### PR DESCRIPTION
**Pull request by tomkr**
Most of this is the static files that are a result of my project. The one thing I wasn't able to test was the integration with the item in in the template. If that's not working as expected (it should pass the id to the Viewer component so that it can render the embed popup properly), let me know and we can work something out.

If there are things that need changing in the assets, please fire up an issue on [embedr](http://github.com/tomkr/embedr/). Thanks in advance.

### CODE REVIEW

**Comment by mzeinstra** [comment]
This is part of #28 I see that @klokan is probably out of office for the next few days (Congratulations!). @o1da can you accept this request so we can check it for bugs before our public demo on Thursday?

**Comment by tomkr** [comment]
I realised there are issues with the image paths in the viewer, so they won't work yet, but I'm working on a fix.

**Comment by tomkr** [comment]
@mzeinstra The discussed fix for the image paths has been pushed and is part of this PR too now.

**Comment by o1da** [comment]
It is deployed. It looks OK, I have realized only two small problems:
- It tries to download some missing icons
- If you have sequence (http://media.embedr.eu/test2) switching icons are overlayed

**Pull request merged**
