### PR TITLE
Viewer updates

### PR DESCRIPTION
**Pull request by tomkr**
Here are some more tweaks to the viewer, with a slightly updated design and new images.

I also have a question: does the item object in the template have a height and width value? It would be useful to have this in the viewer javascript. If so are they simply item.height and item.width? Thanks a lot.

### CODE REVIEW

**Comment by o1da** [comment]
Yes, I will do it tomorrow, please contact me after the demo presentation.

**Comment by mzeinstra** [comment]
We are on at 16:30, i would rather have it live before that time, if that is possible.

**Comment by o1da** [comment]
Oh I see, it isn't problem, it is deployed now.

**Comment by o1da** [comment]
@tomkr 
I forgot to response for your question about item sizes on template. 
So there is my answer. It is available in the template, but it isn't as simple as item.height and item.width. Because 1 item can has many images, so there is a dict `item.image_meta` which has source urls of images as a key. And if you use this key you get another dict with image metadata for particular image. So it can be used like:

*`item.image_meta[item.url[0]]['height']` for height of 1st image in sequence (or if you have just 1 image)
*`item.image_meta[item.url[1]]['width']` for width of 2nd image in sequence

Should I merge #53 now or do you update it first according this info?

**Comment by tomkr** [comment]
#53 can be merged as I use a different way to get the width and height for now, so that one should be good to go.

**Pull request merged**
