### PR TITLE
Updated the viewer.

### PR DESCRIPTION
**Pull request by tomkr**
- New static files.
- Some tweaks to the template.

The update includes a patched openseadragon. One issue I had was that the  key
in the tilesource broke the viewer. Perhaps it should be removed from the python
code.

### CODE REVIEW

**Comment by mzeinstra** [comment]
@klokan @o1da from my end you can merge this and #82.

**Comment by mzeinstra** [comment]
@o1da am I right that the code in this pull request are not yet on the server?

**Comment by o1da** [comment]
It isn't deployed yet. Viewer is broken from this commit - there is static image address, so I have reverted it yet.

**Comment by mzeinstra** [comment]
@o1da is this an action for @tomkr or can we fix this ourselves?

**Comment by o1da** [comment]
I don't know what is a difference between previously used `React.render` and `ReactDOM.render` from this pull request, but the new one tried to load IIIF image from URL with original static image. So I have just removed this unuseful URL from tilesources and it works - it is deployed.

Another thing from this pull request isn't clear to me - why the `sequenceMode: true` setting was removed from the OpenSeadragon configuration? How the items with sequences will be shown?

**Comment by tomkr** [comment]
These two things likely have to do with the newer version of OSD that I included. It did something weird with the `url` key, trying to fetch it. I meant to put that in my description, but it was quite unclear there.

The `sequenceMode: true` tried to display controls for the sequences, which is not currently supported by embedr. There is an open issue there for supporting sequences, so once that is resolved it can be put to true again. I hope that clarifies these things.

**Comment by o1da** [comment]
Which issue connected with the sequences do you mean? The sequences are implemented from early stage of this project. It was tested already.

**Comment by tomkr** [comment]
It is not implemented in the embedr viewer. So the issue is on that project.

**Comment by mzeinstra** [comment]
There are no sequences in the front-end at the moment, we were unsure how to implement it properly with regards to embeds, also of facebook and twitter. We will support it in the future.

**Pull request merged**
