### PR TITLE
Added Facebook, Twitter and Google Analytics integrations

### PR DESCRIPTION
**Pull request by mzeinstra**
Made some small changes to the viewer, adding open Graph and Twitter integration, for the possibility of people referring directly to the viewer. Also added Google Analytics to track embedded frames.

Not necessary to accept and push to production immediately, as I expect more changes before the end of this month.

### CODE REVIEW

**Comment by o1da** [comment]
Ok, I'm going to wait for your notice.

**Comment by mzeinstra** [comment]
I made additional changes to the viewer and how oEmbed works. I believe we my final build is failing because of changes made to the ingest side of this repo. 

If that is true, and has nothing to do with my changes than I believe this also solves: #76 As far as I am concerned this could be merged if the remaning failing test is due to other changes in the project.

**Comment by o1da** [comment]
I have just change tests - it wasn't actualized according last changes.

Should I merge this pull request now?

**Comment by mzeinstra** [comment]
You can merge this pull request. I don't expect me to do more development.

**Comment by o1da** [comment]
It is deployed, it seems to be OK.

**Pull request merged**
